module.exports = {
  employee: require("./employee"),
  supplier: require("./supplier"),
  custody: require("./custody"),
  custodyEmployee: require("./custodyEmployee"),
  material: require("./material"),
  materialEmployee: require("./materialEmployee"),
  buyRequest: require("./buyRequest"),
  role: require("./role"),
  color: require("./color"),
  size: require("./size"),
  model: require("./model"),
  stage: require("./stage"),
  client: require("./client"),
  materialType: require("./materialType"),
};
