module.exports = {
  Employee: require("./employeeModel"),
  Custody: require("./custodyModel"),
  Supplier: require("./supplierModel"),
  Material: require("./materialModel"),
  SupplierCustody: require("./supplierCustodyModel"),
  SupplierMaterial: require("./supplierMaterialModel"),
  CustodyEmployee: require("./custodyEmployeeModel"),
  MaterialEmployee: require("./materialEmployeeModel"),
  Carton: require("./cartonModel"),
  Model: require("./modelModel"),
  Shipment: require("./shipmentModel"),
  Client: require("./clientModel"),
  Order: require("./orderModel"),
  BuyRequest: require("./buyRequestModel"),
  Role: require("./roleModel"),
  Color: require("./colorModel"),
  Size: require("./sizeModel"),
  Stage: require("./stageModel"),
  MaterialType: require("./materialTypeModel"),
};
