module.exports = {
  employeeController: require("./employeeController"),
  supplierController: require("./supplierController"),
  custodyController: require("./custodyController"),
  custodyEmployeeController: require("./custodyEmployeeController"),
  materialController: require("./materialController"),
  materialEmployeeController: require("./materialEmployeeController"),
  buyRequestController: require("./buyRequestController"),
  roleController: require("./roleController"),
  colorController: require("./colorController"),
  sizeController: require("./sizeController"),
  modelController: require("./modelController"),
  stageController: require("./stageController"),
  clientController: require("./clientController"),
  materialTypeController: require("./materialTypeController"),
  cartonController: require("./cartonController"),
  shipmentController: require("./shipmentController"),
  orderController: require("./orderController"),
  machineTypeController: require("./machineTypeController"),
  userRoleController: require("./userRoleController"),
  userController: require("./userController"),
  authController: require("./authController"),
  userEmployeeController: require("./userEmployeeController"),
  cardController: require("./cardController"),
  salaryController: require("./salaryController"),
};
